name: Tests

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php:
          - '8.1'
        experimental:
          - false
        include:
          - php: "8.1"
            composer-options: "--ignore-platform-reqs"
            experimental: true

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring
          tools: "composer:v2"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest ${{ matrix.composer-options }}

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress --no-suggest ${{ matrix.composer-options }}

      - name: "Run tests"
        run: ./vendor/bin/phpunit -c phpunit.xml

  cs:
    name: Codestyle check on PHP 8.1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.1'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run tests
        run: ./vendor/bin/phpcs

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.1'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit 512M
