name: Tests

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
        include:
          - php: '7.2'
            phpunit: '"^7||^8"'
          - php: '8.1'
            phpunit: '"^9"'
          - php: '8.2'
            phpunit: '"^9"'
          - php: '8.3'
            phpunit: '"^9"'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring
          tools: "composer:v2"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install specific version of phpunit "
        if: ${{ matrix.phpunit  }}
        run: composer require --no-interaction --no-progress --no-suggest phpunit/phpunit:${{ matrix.phpunit }}

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress --no-suggest

      - name: "Run tests"
        run: ./vendor/bin/phpunit -c phpunit.xml

  cs:
    name: Codestyle check on PHP 7.2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.2'
        phpunit:
          - '"^7||^8"'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install specific version of phpunit "
        if: ${{ matrix.phpunit  }}
        run: composer require --no-interaction --no-progress --no-suggest phpunit/phpunit:${{ matrix.phpunit }}

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run tests
        run: ./vendor/bin/phpcs

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.2'
        phpunit:
          - '"^7||^8"'

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install specific version of phpunit "
        if: ${{ matrix.phpunit  }}
        run: composer require --no-interaction --no-progress --no-suggest phpunit/phpunit:${{ matrix.phpunit }}

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit 512M
